### ISSUE TITLE
Fails to run on Linux

### ISSUE THREAD

**Issue by iMichka** [monsieurvideo/get-flash-videos#215]
Hi

I am one of the Linuxbrew maintainers. We are packaging get-flash-videos in our package manager, which is based on the homebrew package manager for OS X.

We have the following sanity check to see if get-flash-videos works fine:

> get_flash_videos http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm

This fails with the following error:

> Using method 'bbc' plugin version 0.01 for http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Downloading http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Error: Can't use string ("<?xml version="1.0" encoding="UT"...) as a SCALAR ref while "strict refs" in use at /home/linuxbrew/.linuxbrew/Cellar/get-flash-videos/1.25.93/lib/perl5/FlashVideo/Site/Bbc.pm line 88.
Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.
Please confirm that the URL is valid and that you are running the latest
version of get-flash-videos.
If the latest version does not support this site please create a bug
report at https://github.com/monsieurvideo/get-flash-videos making
sure you include the output with --debug enabled. Alternatively,
fix it yourself and send us a pull request.
Couldn't download any videos.

The same command line works fine on mac. I guess there is something with the `$$content` variable in Bbc.pm at line 88, but my perl knowledge stops here. Could you please have a look?

Issue on our bugtracker for reference: https://github.com/Linuxbrew/homebrew-core/pull/3467

**Comment by pcwalden** [comment]
The latest github version works for me on Fedora 23 with perl v5.22.2.

> get_flash_videos-1.25.93 http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
> Using method 'bbc' plugin version 0.01 for http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
> Downloading http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
> RTMPDump v2.4
> (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
> Connecting ...
> INFO: Connected...
> Starting download at: 0.000 kB
> INFO: Metadata:
> INFO:   duration              283.58
> INFO:   moovPosition          53109262.00
> INFO:   width                 688.00
> INFO:   height                384.00
> INFO:   videocodecid          avc1
> INFO:   audiocodecid          mp4a
> INFO:   avcprofile            77.00
> INFO:   avclevel              31.00
> INFO:   aacaot                2.00
> INFO:   videoframerate        25.00
> INFO:   audiosamplerate       48000.00
> INFO:   audiochannels         1.00
> INFO: trackinfo:
> INFO:   length                7089000.00
> INFO:   timescale             25000.00
> INFO:   language              eng
> INFO: sampledescription:
> INFO:   sampletype            avc1
> INFO:   length                13612032.00
> INFO:   timescale             48000.00
> INFO:   language              eng
> INFO: sampledescription:
> INFO:   sampletype            mp4a
> BBC_-__Do_whatever_it_takes_to_get_him_to_talk.flv: 99% (51977.68 / 52238.87 KiB)
> Done. Saved 53477629 bytes to BBC_-__Do_whatever_it_takes_to_get_him_to_talk.flv
> [pwalden@walden3 Videos]$

**Comment by njtaylor** [comment]
Just tried running here on OpenBSD... (BSD Unix rather than Linux), also tried on Debian and both worked.

The issue might be BBC may only work within the UK, for this. But doesn't explain mac working, unless some VPN is being used. That part of code is not normally run, suggesting something different is being return for some reason such as region checking.

Try running with the -d flag on Linuxbrew, the extra info might help track this down.
Only need something like this to start with, may not even be getting this far

$ get_flash_videos -d http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm 
1 plugins installed:
- Hulu.pm
Trying to open plugin ~/.get_flash_videos/plugins/News.pm
Trying to open plugin ~/.get_flash_videos/plugins/Bbc.pm
Using method 'bbc' plugin version 0.01 for http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Downloading http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
-> GET http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
<- 301 text/html; charset=iso-8859-1 266 (266): UTF8 off, ASCII, 266 characters 266 bytes
-> GET http://news.bbc.co.uk/1/hi/programmes/hardtalk/9560793.stm
<- 200 text/html (74047): UTF8 on, non-ASCII, 74047 characters 74049 bytes
-> GET http://news.bbc.co.uk/media/emp/9560000/9560700/9560793.xml
<- 200 text/xml (1446): UTF8 on, ASCII, 1446 characters 1446 bytes
-> GET http://open.live.bbc.co.uk/mediaselector/4/mtis/stream/p00jq9g1
<- 200 text/xml (4790): UTF8 on, ASCII, 4790 characters 4790 bytes
FlashVideo::RTMPDownloader=HASH(0xb7ab3be1118)

**Comment by pcwalden** [comment]
> The issue might be BBC may only work within the UK, for this.

I am in the US and it works here.

**Comment by iMichka** [comment]
The error happens both on our Travis and circle builds (Ubuntu Trusty), and for me locally on ubuntu 17.04 (zesty). I'm sitting in Germany. But I can run the command with my mac, so I doubt there is any country limitation here.

Here is the output with `-d`:

```
$ get_flash_videos -d http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
No plugins installed
Trying to open plugin ~/.get_flash_videos/plugins/News.pm
Trying to open plugin ~/.get_flash_videos/plugins/Bbc.pm
Using method 'bbc' plugin version 0.01 for http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Downloading http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
-> GET http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
<- 301 text/html; charset=iso-8859-1 266 (266)
-> GET http://news.bbc.co.uk/1/hi/programmes/hardtalk/9560793.stm
<- 200 text/html (76337)
-> GET http://news.bbc.co.uk/media/emp/9560000/9560700/9560793.xml
<- 200 text/xml (1446)
Error: Can't use string ("<?xml version="1.0" encoding="UT"...) as a SCALAR ref while "strict refs" in use at /home/linuxbrew/.linuxbrew/Cellar/get-flash-videos/1.25.93/lib/perl5/FlashVideo/Site/Bbc.pm line 88.

Couldn't extract Flash movie URL. This site may need specific support adding,
or fixing.

Please confirm that the URL is valid and that you are running the latest
version of get-flash-videos.

If the latest version does not support this site please create a bug
report at https://github.com/monsieurvideo/get-flash-videos making
sure you include the output with --debug enabled. Alternatively,
fix it yourself and send us a pull request.
Couldn't download any videos.
```

**Comment by pcwalden** [comment]
Assuming you are using the latest build, the error is originating from this statement:

`$playlist = from_xml($$content, KeyAttr => {item => 'kind'})`

If $content is in fact the string 

> ("<?xml version="1.0" encoding="UT"...)

, and not a reference to a string, then the $$ dereference would complain.

I do not know why this is working on my instance or the mac.

Whate version of perl are you using? (perl -V)

**Comment by njtaylor** [comment]
The fix to the code is to change `from_xml($$content,` to `from_xml(\$content,`
but that doesn't explain why the code is being reached because the previous from_xml must fail to find the expected xml content, and unlikely to work just by fixing this piece of code that is not normally run (it's to fix occasional site issues, and never would have worked).

The download of
http://news.bbc.co.uk/media/emp/9560000/9560700/9560793.xml
has the same length so have to look at the difference between the contents.

The mac working might point to the agent setting in the HTTP GET being different, if no difference in the download then the other is XML::Simple version of lib-xml-simple-perl, debian uses 2.20-1, OpenBSD uses 2.24, for some reason the mac version works and the other doesn't. Need to determine where the problem lies I made temporary changes by copying Bbc.pm to the plugins directory. as in code below to print the extra things..

You could try downloading http://news.bbc.co.uk/media/emp/9560000/9560700/9560793.xml first

I can use this on OpenBSD
ftp http://news.bbc.co.uk/media/emp/9560000/9560700/9560793.xml

Need to use curl/wget instead.

Then would expect to see XML with item kind in the download

$ grep kind 9560793.xml                                                                                                                                                       
    <item kind="programme" duration="283"

Compare between the working and non-working, but curl/wget aren't used by get_flash_videos, so if the same, means need to move on and look at exactly what get_flash_videos downloads, that means adding a block of code after the eval { from_xml.

```
  my $playlist = eval { from_xml($browser, KeyAttr => {item => 'kind'}) };

  {
    use Data::Dumper;
    my $content = $browser->content;
    print "User Agent: ".$browser->agent()."\n";
    print $content;
    my $playlist1 = from_xml(\$content, KeyAttr => {item => 'kind'});
    print Data::Dumper->Dumper($playlist1);
  }
  if ($@) {
    # Try to fix their potentially broken XML..
    my $content = $browser->content;
    if ($content !~ m{</media>}) {
      $content .= "\n</media></item></playlist>\n";
    }
    $playlist = from_xml(\$content, KeyAttr => {item => 'kind'});
  }
```
First copy Bbc.pm to ~/.get_flash_videos/plugins and amend, once finished remove, get_flash_video will pick up the alternative Bbc.pm, check before use by

```
$ perl -c .get_flash_videos/plugins/Bbc.pm 
.get_flash_videos/plugins/Bbc.pm syntax OK
```

**Comment by njtaylor** [comment]
Bbc.pm modified, to fix strict ref issue in from_xml call, and provide additional debug information.

**Comment by pcwalden** [comment]
FYI, still working for me after this update.

**Comment by iMichka** [comment]
Ok I tested the patched plugin. It did output more stuff than before, and especially:

> Must have XML::Simple to download 1 videos
> A required Perl module for downloading this video is not installed.

Adding that dependency fixed it. I could even run get_flash_videos without the modified plugin, so the problem was that this dependency was missing. For me everything is fine now, and we can close this issue.

The error message was way better with the modified code so you may want to change that part for the next release. Thanks everybody for the quick help!

**Comment by njtaylor** [comment]
Thanks for feedback, closing issue - as missing dependency.
